/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ProfileViewsRouteImport } from './routes/profile.views'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts.$scriptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileViewsRoute = ProfileViewsRouteImport.update({
  id: '/profile/views',
  path: '/profile/views',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/people': typeof PeopleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/views': typeof ProfileViewsRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/people': typeof PeopleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/views': typeof ProfileViewsRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/people': typeof PeopleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/views': typeof ProfileViewsRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/people'
    | '/verify-email'
    | '/profile/$userId'
    | '/profile/views'
    | '/scripts/$scriptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/people'
    | '/verify-email'
    | '/profile/$userId'
    | '/profile/views'
    | '/scripts/$scriptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/people'
    | '/verify-email'
    | '/profile/$userId'
    | '/profile/views'
    | '/scripts/$scriptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  PeopleRoute: typeof PeopleRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileViewsRoute: typeof ProfileViewsRoute
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/views': {
      id: '/profile/views'
      path: '/profile/views'
      fullPath: '/profile/views'
      preLoaderRoute: typeof ProfileViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  PeopleRoute: PeopleRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileViewsRoute: ProfileViewsRoute,
  ScriptsScriptIdRoute: ScriptsScriptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
